### ISSUE TITLE
Latest version doesn't run on Ubuntu Artful (Core Dump)

### ISSUE THREAD

**Issue by antony** [cmauri/eviacam#15]
```bash
ant@vanta:~/$ eviacam

(eviacam:7900): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
Trace/breakpoint trap (core dumped)
```

Not sure what version numbers you'd need to know, so let me know if you need more information:

```
ant@vanta:~/Projects/eviacam$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
```

**Comment by kyrios123** [comment]
This is probably linked to the changes made for issue #14

**Comment by cmauri** [comment]
Hello,

Yes, it seems that eviacam binary shipped with artful (and most likely debian strech also) is broken.

This issue stems from the fact that artful provides wxWidgets built against gtk-2 and libopencv against gtk-3. Mixing gtk versions is not allowed.

AFAIU, this issue should be solved in those distros (i.e. upgrading wxWidgets to use gtk-3). In the meantime you may want to compile eviacam yourself. See https://github.com/cmauri/eviacam/issues/14#issuecomment-369415170 for more information.

**Comment by antony** [comment]
Ah I got some issues compiling it from source too - I will dig out the exact error I received.

**Comment by cmauri** [comment]
Make sure you are using the latest eViacam release (2.1.3) and that you've compiled and installed wxWidgets yourself with gtk-3 support.

**Comment by Daniel78ar** [comment]
Good afternoon. Well, in my case, I solve the issue with the next steps. First download wxwidgets 3.1.2 from wxwidgetx.org and unzip and install with sudo ./configure in a console (konsole or tilix) make and make install. After this download the viacam from the source from https://eviacam.crea-si.com/index_es.php (codigo fuente/source code 2.1.1 or new). Install in synaptics the next files gtk2-dev libopencv-dev because the dependencies requeriments from evince. After this 
Unzip the file in the personal folder that you need to indicate the eviacam folder, and when installing it do the following: sudo ./configure and then make -i and make install -i, to ignore the errors. This is because the versions of wxwidgets and eviacam are updated when you install the files from compilation process. The next thing is to go to https://packages.ubuntu.com/eoan/eviacam, download the file en deb format and install with gdebi gtk or in a console (gdebi *.deb or eviacam) and install the file. This solve the issue. I test the program eviacam and works in ubuntu 18.04!

**Comment by Daniel78ar** [comment]
And do not forget compile wxwigdets with gtk3 support. I forgot: before do the first step install eviacam from synaptic before beggining with the steps that I said above.
